theme: minima

# meta
title: My Tutorial Blog
author: Ajay
email: ajay@ajays.space
description: > An ex-nursing student turned graduate computer science student trying to find his footing.

# social links
twitter_username: ajaystxus
github_username: ajaystxus

# miscellaneous
show_excerpts: true # set to false to remove excerpts on the homepage
